/* eslint-disable sort-keys */
import { cva } from 'class-variance-authority';

export const buttonVariants = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'rounded-md',
    'text-sm',
    'font-medium',
    'ring-offset-background',
    'transition-colors',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-ring',
    'focus-visible:ring-offset-2',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    // text styles if variant is ghost/link
    'data-[variant=ghost]:h-fit',
    'data-[variant=ghost]:p-0',
    'data-[variant=link]:h-fit',
    'data-[variant=link]:p-0',
  ],
  {
    variants: {
      intent: {
        default: [
          'data-[variant=solid]:bg-primary',
          'data-[variant=solid]:text-primary-foreground',
          'data-[variant=solid]:hover:bg-primary/90',
          'data-[variant=outline]:hover:border-primary',
          'data-[variant=outline]:hover:text-primary',
          'data-[variant=link]:text-primary',
          'data-[variant=ghost]:text-primary',
          'data-[variant=ghost]:hover:text-primary/70',
        ],
        destructive: [
          'data-[variant=solid]:bg-destructive',
          'data-[variant=solid]:text-destructive-foreground',
          'data-[variant=solid]:hover:bg-destructive/90',
          'data-[variant=outline]:hover:border-destructive',
          'data-[variant=outline]:hover:text-destructive',
          'data-[variant=link]:text-destructive',
          'data-[variant=ghost]:text-destructive',
          'data-[variant=ghost]:hover:text-destructive/70',
        ],
        info: [
          'data-[variant=solid]:bg-info',
          'data-[variant=solid]:text-info-foreground',
          'data-[variant=solid]:hover:bg-info/90',
          'data-[variant=outline]:hover:border-info',
          'data-[variant=outline]:hover:text-info',
          'data-[variant=link]:text-info',
          'data-[variant=ghost]:text-info',
          'data-[variant=ghost]:hover:text-info/70',
        ],
        secondary: [
          'data-[variant=solid]:bg-secondary',
          'data-[variant=solid]:text-secondary-foreground',
          'data-[variant=solid]:hover:bg-secondary/80',
          'data-[variant=outline]:hover:border-secondary',
          'data-[variant=outline]:hover:text-secondary-foreground',
          'data-[variant=link]:text-secondary-foreground',
          'data-[variant=ghost]:text-secondary-foreground',
          'data-[variant=ghost]:hover:text-secondary-foreground/70',
        ],
        success: [
          'data-[variant=solid]:bg-success',
          'data-[variant=solid]:text-success-foreground',
          'data-[variant=solid]:hover:bg-success/80',
          'data-[variant=outline]:hover:border-success',
          'data-[variant=outline]:hover:text-success',
          'data-[variant=link]:text-success',
          'data-[variant=ghost]:text-success',
          'data-[variant=ghost]:hover:text-success/70',
        ],
        warning: [
          'data-[variant=solid]:bg-warning',
          'data-[variant=solid]:text-warning-foreground',
          'data-[variant=solid]:hover:bg-warning/80',
          'data-[variant=outline]:hover:border-warning',
          'data-[variant=outline]:hover:text-warning',
          'data-[variant=link]:text-warning',
          'data-[variant=ghost]:text-warning',
          'data-[variant=ghost]:hover:text-warning/70',
        ],
      },
      size: {
        default: ['h-10', 'px-4', 'py-2'],
        sm: ['h-9', 'rounded-md', 'px-3'],
        lg: ['h-11', 'rounded-md', 'px-8'],
        icon: ['size-10'],
      },
      variant: {
        outline: ['border', 'border-input', 'bg-background'],
        solid: [],
        ghost: ['bg-transparent'],
        link: ['underline-offset-4', 'hover:underline'],
      },
    },
    defaultVariants: {
      intent: 'default',
      size: 'default',
      variant: 'solid',
    },
  },
);
